name: Format checking
on:
    pull_request:
        branches:
            - lab1
jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
                  cache: 'npm'
            - run: npm ci && npm run format && npm run lint && npm run lint:style
