name: Format check
on: [pull_request]
jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: npm ci && npm run format && npm run lint && npm run lint:style
